# Generated by Django 4.2.6 on 2024-08-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="author_image",
        ),
        migrations.AlterField(
            model_name="app",
            name="image",
            field=models.ImageField(
                upload_to="articles/images", verbose_name="App image"
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="title",
            field=models.CharField(max_length=100, verbose_name="App title"),
        ),
    ]
