# Generated by Django 4.2.6 on 2024-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0002_remove_app_author_image_alter_app_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="articles/video"),
        ),
    ]
