# Generated by Django 4.2.6 on 2024-08-24 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0003_app_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="video",
        ),
        migrations.AddField(
            model_name="app",
            name="video_url",
            field=models.URLField(
                blank=True,
                validators=[django.core.validators.URLValidator()],
                verbose_name="Video URL",
            ),
        ),
    ]
