# Generated by Django 4.2.6 on 2024-08-25 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0004_remove_app_video_app_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="video_url",
            field=models.FileField(
                blank=True,
                max_length=200,
                upload_to="",
                validators=[django.core.validators.URLValidator()],
                verbose_name="Video URL",
            ),
        ),
    ]
