# Generated by Django 4.2.6 on 2024-08-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0006_remove_app_video_url_app_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="video_file",
            field=models.FileField(
                upload_to="articles/videos", verbose_name="Video file"
            ),
        ),
    ]
