# Generated by Django 4.2.6 on 2024-08-28 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0009_movie_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="Price"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.TextField(max_length=50, verbose_name="Book description"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=5, verbose_name="Book title"),
        ),
    ]
