# Generated by Django 4.2.6 on 2024-08-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0010_book_price_movie_price_alter_book_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="games/thumbnails/"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.TextField(max_length=500, verbose_name="Book description"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Book title"),
        ),
    ]
