# Generated by Django 4.2.6 on 2024-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0011_game_thumbnail_alter_book_content_alter_book_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="Category"),
        ),
        migrations.AddField(
            model_name="app",
            name="description",
            field=models.TextField(
                default=0, max_length=200, verbose_name="App description"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="Category"),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(
                default=0, max_length=200, verbose_name="Book description"
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="Category"),
        ),
        migrations.AddField(
            model_name="game",
            name="description",
            field=models.TextField(
                default=0, max_length=200, verbose_name="Game description"
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="category",
            field=models.CharField(blank=True, max_length=50, verbose_name="Category"),
        ),
        migrations.AddField(
            model_name="movie",
            name="description",
            field=models.TextField(
                default=0, max_length=200, verbose_name="Movie description"
            ),
        ),
        migrations.AlterField(
            model_name="app",
            name="image",
            field=models.ImageField(upload_to="apps/images", verbose_name="App image"),
        ),
        migrations.AlterField(
            model_name="app",
            name="video_file",
            field=models.FileField(upload_to="apps/videos", verbose_name="Video file"),
        ),
        migrations.AlterField(
            model_name="book",
            name="content",
            field=models.TextField(max_length=500, verbose_name="Book content"),
        ),
        migrations.AlterField(
            model_name="game",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                default="default_thumbnail.jpg",
                null=True,
                upload_to="games/thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="content",
            field=models.TextField(max_length=200, verbose_name="Movie content"),
        ),
    ]
