# Generated by Django 4.2.6 on 2024-08-28 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0012_app_category_app_description_book_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="app",
            name="video_file",
        ),
        migrations.RemoveField(
            model_name="book",
            name="description",
        ),
    ]
