# Generated by Django 4.2.6 on 2024-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0013_remove_app_video_file_remove_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="video_file",
            field=models.FileField(
                default=0, upload_to="apps/videos", verbose_name="Video file"
            ),
        ),
    ]
