# Generated by Django 4.2.6 on 2024-08-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0014_app_video_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="video_file",
            field=models.FileField(
                upload_to="movies/videos", verbose_name="Video file"
            ),
        ),
    ]
