# Generated by Django 4.2 on 2024-08-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playstore", "0016_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
